ENV['TWITTER_CONSUMER_KEY'] = 'ftCIdGCfv1w9cUeo1MNLYc2xd'
ENV['TWITTER_CONSUMER_SECRET'] = 'oEO3cHGR9noj5j5sgNBNIW8YU1ufuiU5trfRt8HgGcJF0Y4y3P'

ENV['FACEBOOK_APP_ID'] = '...'
ENV['FACEBOOK_APP_SECRET'] = '...'
